### PR TITLE
Mystify new

### PR DESCRIPTION
**Pull request by VaibhavNITK**
Added logo to left of nav bar

### CODE REVIEW

**Comment by Shashankhs17** [comment]
image

The logo is shifting the entire header section to right. Fix this issue.

**Comment by VaibhavNITK** [comment]
Issue is resolved ig

**Comment by Shashankhs17** [comment]
image
Neither the top nor side navigation bar is visible at this point due to the logo overlapping the top navigation bar.


image
The logo should be on the left side of the screen even in the mobile navigation. It shouldn't be inside the side navigation bar.

**Comment by Shashankhs17** [comment]
Reduce the left margin and check whether it fits properly in all dimensions.

**Pull request closed without merging**
