### PR TITLE
New Post : Why Machine Learning Matters? , Varistor , Automate the industries

### PR DESCRIPTION
**Pull request by Siddhartha15**
**Why Machine Learning Matters?** - A primer on ML and introduction to Supervised Learning 
**Varistor** - Understanding Varistor, it’s characteristics and working
**Automate the Industries** - 'Piston'

### CODE REVIEW

**Comment by salman-bhai** [comment]
@Siddhartha15 recompile the entire blog folder once more to remove the merge conflicts
Use the following commands in the same order

```git
git pull https://github.com/IEEE-NITK/ieee-nitk.github.io/ master
jekyll build --source blog_src/ --destination blog/
git add --all
git commit -m "Merge conflicts fixed"
git push origin blog
```

**Comment by salman-bhai** [comment]
I think you'll have to pull from master and the compile again

**Comment by Siddhartha15** [comment]
Was Not Able to resolve conflicts. Therefore closed it and made new pr again.

**Comment by salman-bhai** [comment]
Merge conflicts haven't been fixed

**Pull request closed without merging**
