### PR TITLE
Team section update

### PR DESCRIPTION
**Pull request by nimbus98**
had git issue with previous PR
This has the file with fixes.

### CODE REVIEW

**Comment by anumehaagrawal** [comment]
@nimbus98, Please add screenshots

**Comment by anumehaagrawal** [comment]
@nimbus98 the executive members have not been updated?

**Comment by nimbus98** [comment]
They have, theres more below. 




heres a pic of it after zooming out

**Comment by anumehaagrawal** [comment]
You should remove the members who have left/alumni. Right @archit-p ?

**Comment by archit-p** [comment]
Yes, we only need this year's executive members. The alumni can be added on a separate tab.

**Comment by anumehaagrawal** [comment]
@nimbus98 Please make the above change

**Comment by nimbus98** [comment]
So I modified the javascript function and the json file to add a new Alumni Section.

**Comment by anumehaagrawal** [comment]
Looks fine to me. Good work!
@archit-p please verify if anything else is needed

**Comment by nimbus98** [comment]
issue #223 is solved

**Pull request merged**
