### PR TITLE
Adding blog information - Mahir

### PR DESCRIPTION
**Pull request by mahirjain25**

### CODE REVIEW

**Comment by salman-bhai** [comment]
@mahirjain25 resolve merge conflicts before sending the PR. You'll have to pull from the master and resolve conflicts internally!

Make sure you compile the blog once before sending the next PR!

**Comment by salman-bhai** [comment]
Run `jekyll serve` locally before sending a PR!

**Comment by salman-bhai** [comment]
@mahirjain25 any updates?

**Comment by adithyabhatkajake** [comment]
Closed due to #57.

**Pull request closed without merging**
