### PR TITLE
Made required changes (Fork changes)

### PR DESCRIPTION
**Pull request by mahirjain25**
Still a few conflicts left to resolve, probably all due to compilation

### CODE REVIEW

**Comment by adithyabhatkajake** [comment]
There is nothing for the authors.

**Comment by mahirjain25** [comment]
I changed the headers, haven't edited authors.yml

**Comment by adithyabhatkajake** [comment]
Can you do a quick commit fixing everything? Let's finish this.

**Comment by mahirjain25** [comment]
Ok, but the author pictures ?
Not everyone has given them I think.

**Comment by adithyabhatkajake** [comment]
I see. We wait, then.

**Comment by salman-bhai** [comment]
Use author-image.jpg for now!

**Comment by salman-bhai** [comment]
it's there in the authors folder

**Comment by salman-bhai** [comment]
Is this PR relevant?

**Comment by mahirjain25** [comment]
I have just made the latest commit. There is a conflict with this branch, but my forked repo can automatically merged with the original repo

**Comment by mahirjain25** [comment]
Oh damn, i pushed these commits to the wrong PR. How do i commit to the previous PR #65

**Comment by adithyabhatkajake** [comment]
Commit 5d3a02d right? I will cherry pick it onto the mahir-branch.

**Comment by adithyabhatkajake** [comment]
@mahirjain25, I have synced your fork with master.

**Comment by mahirjain25** [comment]
I just reset mine with master too, so its all up to date.

**Pull request closed without merging**
