### PR TITLE
CompSoc content changed + Github Links added

### LINKED ISSUE #130: Link project titles to Github Repositories
Right now the CompSoc page just lists all the projects and their descriptions. It would be better to have a small GitHub icon or a `[Github]` text beside the title linking the repo of the project.

### PR DESCRIPTION
**Pull request by pvgupta24**
Closes #130 #131 .
* Project content taken from certificates. Modifications might be needed.
* Research Group brief information hardcoded in `compsoc.html`. 

@salman-bhai @kaushiksk , Please review.

### CODE REVIEW

**Comment by pvgupta24** [comment]
screenshot from 2018-05-12 19-18-18

@salman-bhai made the changes.

**Comment by kaushiksk** [comment]
@pvgupta24  I also wanted changes to the COMPSOC tab in the home page of the website under `#sigs`. Currently it reads 

```


The Computer Society is a conglomeration of students with a passion for Computer Science and Information Technology. 
This SIG is a wonderful platform for those who want to gain expertise in computer based technology.

In true divide-and-conquer spirit, the SIG is subcategorized many groups like High Performance Computing,
Security and Systems Programming,Databases, Data Structures and Algorithms,Web / Mobile Application Development,
Networks and Communication,Computer Graphics, Vision and Virtual Reality,Data, Machine Learning and Artificial Intelligence

```

You may change it to

```
The Computer Society is a conglomeration of students with a passion for Computer Science and Information Technology. 
This SIG is a wonderful platform for those who want to gain expertise in computer based technology.

In true divide-and-conquer spirit, the SIG is subcategorized into three research groups, namely
  - Intelligence
  - Systems
  - Theorteical Computer Science

```

(Use bullets)

**Comment by kaushiksk** [comment]
Yes that's exactly what I wanted.

See if you can indent the bullet points.
And after the bullets add another sentence
"Activities are carried out by members of the research groups under their
respective heads and co-heads. "

Regards,
Kaushik S Kalmady

**Comment by pvgupta24** [comment]
Fixed the issues. :+1:

**Pull request merged**
