### PR TITLE
New articles for the week added

### PR DESCRIPTION
**Pull request by salman-bhai**
Articles added:
* Technology in Sports
* Hashing in Competitive Programming

Author Information and other details added as well!

@viggi-v Any Issues with any other articles let me know in this post itself!

### CODE REVIEW

**Comment by adithyabhatkajake** [comment]
Hashing Article: No author image?
Please add `use_math: true` in the header of the post and write normal latex equations. Converting equations into images can be painfully boring.

**Comment by salman-bhai** [comment]
I'll do that @adithyabhatkajake

**Comment by adithyabhatkajake** [comment]
Don't merge commits like this in the future. It will break everything.
I am fixing it for now.

**Comment by salman-bhai** [comment]
Cool cool. Also try squashing the commits. Simply the number of commits increases to a big number!

**Pull request merged**
