### PR TITLE
electrika website

### PR DESCRIPTION
**Pull request by Shashankhs17**
Screenshot (308)
Screenshot (309)
Screenshot (310)
Screenshot (311)
Screenshot (312)

### CODE REVIEW

**Comment by nishant-nayak** [comment]
- [ ] Update the timeline. Info can be shared by Rohan Rao.
- [ ] Bourn Bon sponsor logo links back to IEEE NITK website, change the link to Bourn Bon link. If there's no link, remove the `<a>` tag.

**Review by nishant-nayak — CHANGES_REQUESTED** [review]
@Shashankhs17 
- [x] Update the timeline. Info can be shared by Rohan Rao.
- [ ] Bourn Bon sponsor logo links back to IEEE NITK website, change the link to Bourn Bon link. If there's no link, remove the `<a>` tag.

**Comment by Shashankhs17** [comment]
Screenshot (317)

image

Image link is now pointing to Bourbon Website
Schedule is updated

**Review by nishant-nayak — APPROVED** [review]
LGTM

**Pull request merged**
