### PR TITLE
Site Update 1

### PR DESCRIPTION
**Pull request by nimbus98**
Here are the updates listed:

1. Edited Navbar with Dropdown for SIGs
2. Fixed Bugs here and there
3. Added IAS SIG
4. Edited Team sections in homepage and team page as requested
5. Added Registration Codes for each SIG
6. Added Projects for every SIG along with Flowcharts
7. Added Flowchart for Join Us page
8. Added WiTS link on the homepage with date
9. Removed Published papers from the homepage, and improved the Publications page
10. Added IEEE Bangalore section and IEEE NITK Logo in the description
11. Added IEEE Bangalore section link in the footer
12. Diode changed to CAS/SPS everywhere with relevant description.
13. Changed picture for WiE in SIG subsection in homepage.
14. Loaded the Teko Font

I'm guessing those are most of what I've done so far.
I have the following changes left which I will be adding (hopefully) by tomorrow:
1.Editing events section
2.Adding Achievements section and removing its subsection from the home page.
3. Adding "NITK Student Branch: 98631" in the description

### CODE REVIEW

**Comment by nimbus98** [comment]
Update 1.5:
1. Fixed img tags with alt attribute to prevent build fails in Travis CI.
2. Updated Join Us Page with more information provided by Samarth.
3. Added Student Branch Code in Description in bold.

**Comment by nimbus98** [comment]
Update 1.7: Made Achievements Section and removed it from Home Page

**Comment by salman-bhai** [comment]
@anumehaagrawal kindly create a release of the website by going [here](https://github.com/IEEE-NITK/ieee-nitk.github.io/releases) once you merge the MR!

**Comment by nimbus98** [comment]
Thank you!
Here are some screenshots:

**Comment by SamarthBonthala** [comment]
@nimbus98 Amazing work with updating the website. I have a few suggestions:
1. You can remove the mindmap saying Benefits of IEEE NITK Student Branch
2. Can you please change the title "Course Registration Code" to Chapter Registration Code on all SIG sidebars?

**Comment by nimbus98** [comment]
Thank you!
And yes, they are done. ^_^

**Comment by anumehaagrawal** [comment]
There are a couple of changes that need to be done :  
1.  The flowchart for yearlong projects is not responsive
screenshot from 2018-12-09 20-21-14
2. The logo isnt fitting in the navbar
screenshot from 2018-12-09 20-18-20
3. The text needs to be within the orange background
screenshot from 2018-12-09 20-20-18
4. I am unable to see contents in the footer
screenshot from 2018-12-09 20-19-09

**Comment by nimbus98** [comment]
Sorry about the responsiveness problem, I've fixed that.
Not sure about the wie.jpg image because it exists..

**Comment by anumehaagrawal** [comment]
The logo looks fine now however there are still a few things that i see
screenshot from 2018-12-10 16-39-22
screenshot from 2018-12-10 16-39-49

**Comment by nimbus98** [comment]
Update 2.0
1. Edited entire events section, added appropriate facebook posts for each event as well
2. Added projects 2018 section for each SIG
3. Improved responsiveness of flowcharts once again

**Comment by anumehaagrawal** [comment]
Great work @nimbus98 !

**Pull request merged**
