### PR TITLE
Faculty edits

### PR DESCRIPTION
**Pull request by nimbus98**
Added Dr. B Venkatesa Perumal back as CAS faculty advisor.

### CODE REVIEW

**Comment by anumehaagrawal** [comment]
The travis build is failing. Please fix the errors so the build is successful

**Comment by nimbus98** [comment]
test

**Comment by salman-bhai** [comment]
Certain images have gone missing, kindly replace them appropriately!

**Comment by salman-bhai** [comment]
@nimbus98 any updates here?

**Comment by nimbus98** [comment]
yeah it works now

**Pull request merged**
